README.md
client/templates/movies.html
client/templates/results.js
client/templates/search.html
server/server.js

Added Couch Potato integration

---

client/templates/home.html

corrected typo "alrady" and changed wording from downloaded to "in library"

corrected typo "alrady" 

---

client/templates/home.html
client/templates/home.js
client/templates/movies.html
client/templates/plex.html
client/templates/plex.js
client/templates/results.js
server/server.js

Now when adding a request the User is attached to the movies collection. 
This shows in the “View Requests!” list, I am only showing who requested the movie to the logged in admin since some people might not want to show who they are shared with?
It should attach to the pushBullet title, please test this as i do not use pushBullet.

Add Plex user to movies collection and PushBullet

---

client/main.js
client/templates/sonarr.html
client/templates/sonarr.js

The content on the test page may need tweaking as I am not sure what exactly is required. Hopefully this helps any!

Dev Sonarr Test Page

---

client/templates/couchpotato.html
client/templates/couchpotato.js
client/templates/sickrage.html
client/templates/sickrage.js
client/templates/sonarr.html
client/templates/sonarr.js

I updated the loader template so it can be used as an icon right next to the connection and status fields. I will revert it if you would like.
#59

Moved Inline JS To Separate Files - Couchpotato & SickRage

---

.meteor/packages
.meteor/versions
client/templates/search.html
client/templates/searchresults.html
client/templates/searchresults.js
public/stylesheets/style.css
server/server.js

I've expanded a little on TV show selection by adding a modal dialog that asks the user if they wish to request only new episodes or all episodes. There is still more work to be done here but the feature works as advertised.

More flexible TV show requests

---

client/templates/admin/admin.html

Fixed typo at line 131. "QTest" to "Test"

modified:   client/templates/admin/admin.html

---

client/lib/stylesheets/_admin.scss
client/lib/stylesheets/styles.scss
client/templates/admin/admin.html
client/templates/admin/admin.js
server/methods/admin/version.js

Better styling and the form reset (Meteor bug) doesn’t change what
you’re viewing.

New settings page

---

.meteor/packages
.meteor/versions
client/lib/stylesheets/_admin.scss
client/lib/stylesheets/styles.scss
client/templates/admin/admin.html
client/templates/admin/admin.js
client/templates/layout/layout.html
lib/routes/routes.js
packages/npm-container/.npm/package/npm-shrinkwrap.json
server/methods/admin/version.js

Reverts lokenx/plexrequests-meteor#155

Revert 2dd6544bdcdcaf63c4cedf16c2b4db183c93049e

---

client/templates/admin/admin.html
client/templates/admin/admin.js
server/methods/admin/sonarrProfiles.js

TODO
Fixes #190
Requires https://github.com/lokenx/sonarrwrapper/pull/1
Any feedback is welcome, not that experienced in Meteor

Select Sonarr profile from list

---

client/templates/layout/layout.html

Fix typo "configre" -> "configure"

Fix typo: configre

---

README.md

typo in url!

---

server/methods/authentication/plexAuthentication.js

Fixed issue #253 using plex auth when not having friends

---

client/head.html

fixed the apple touch icon icon

Update head.html with fixed apple touch icon

---

client/helpers/bert.js
client/lib/stylesheets/_loading.scss
client/templates/admin/admin.html
client/templates/admin/admin.js
client/templates/home/home-alt.html
client/templates/home/home.html
client/templates/home/home.js
client/templates/layout/layout.html
client/templates/layout/layout.js
client/templates/requests/requests.html
client/templates/requests/requests.js
client/templates/search/item.html
client/templates/search/search.html
client/templates/search/search.js
lib/collections/collections.js
lib/collections/publish.js

The html files seemed very inconsistent, but it seems like most of them were using two spaces, so I switched them all over to that. If tabs are preferred it would be very quick to change over. Planning on tackling the javascript at some point as well.

More consistent indentation

---

.gitignore
docker-compose.yml

updated to version 2 syntax
made containers restart automatically
#402

Docker-compose update

---

lib/collections/collections.js
server/methods/search/requestMovie.js

Fixes error when approving radarr movie requests

Fixed undefined year during request approval when using radarr

---

client/lib/stylesheets/_search.scss
client/templates/requests/requests.js
client/templates/search/search.html
client/templates/search/search.js
server/methods/helpers/movies/TMDBSearchMethods.js

I used the .NET version for Plex Requests for a while before switching to this version. A convenient feature it had was a drop down box that allows you to auto search for movies currently in the theaters as well as due to be released soon. This adds that feature here as well. A reusable function could be made, but otherwise it's a very minor but useful addition.

Add Extra Movie Search Button

---

client/lib/stylesheets/_home.scss
client/lib/stylesheets/_navbar.scss
client/lib/stylesheets/_search.scss
client/templates/layout/layout.html

- Adjusted the navbar to fit mobile displays more cleanly
- Added some colour to the search bar icon
- Fixed some margins related to the search field on some window sizes

Adjust Navbar/Search

---

README.md
client/templates/admin/admin.html
client/templates/admin/admin.js
lib/collections/collections.js
server/methods/admin/adminMethods.js
server/methods/notifications/telegramNotification.js
server/methods/search/sendNotification.js

Closes #412.
Same as #497 but separated into a specific branch.

Add Telegram Notification Support

---

client/templates/admin/admin.html
lib/collections/collections.js
server/methods/notifications/pushbulletNotification.js

- New pull request with better code for Pushbullet notification
- New pull requests because I changed repository/branches

Add Pushbullet Device ID Support

---

README.md

No longer known as Plex Requests.net to my knowledge

Plex Requests.net => Ombi

---

client/templates/search/search.js

Fix TV search animation

---

server/methods/search/requestMovie.js

Needs to be added so the ID can be used by notifications

Add IMDB ID to variable request
